### ISSUE TITLE
Getting FIFO data only returns 6 bytes

### ISSUE THREAD

**Issue by WadeHenderson** [STMicroelectronics/iis2iclx-pid#1]
The function for reading the 3kB FIFO has a 6 hard coded as the read length only for `IIS2ICLX_FIFO_DATA_OUT_X_L`. There doesn't seem to be any other way to read the whole buffer once it is full.

iis2iclx_reg.c line 1078
```
/**
  * @brief  FIFO data output.[get]
  *
  * @param  ctx    Read / write interface definitions.(ptr)
  * @param  buff   Buffer that stores data read
  * @retval        Interface status (MANDATORY: return 0 -> no Error).
  *
  */
int32_t iis2iclx_fifo_out_raw_get(stmdev_ctx_t *ctx, uint8_t *buff)
{
  int32_t ret;

  ret = iis2iclx_read_reg(ctx, IIS2ICLX_FIFO_DATA_OUT_X_L, buff, 6);

  return ret;
}
```

**Comment by avisconti** [comment]
> The function for reading the 3kB FIFO has a 6 hard coded as the read length only for `IIS2ICLX_FIFO_DATA_OUT_X_L`. There doesn't seem to be any other way to read the whole buffer once it is full.
> 
> iis2iclx_reg.c line 1078
> 
> ```
> /**
>   * @brief  FIFO data output.[get]
>   *
>   * @param  ctx    Read / write interface definitions.(ptr)
>   * @param  buff   Buffer that stores data read
>   * @retval        Interface status (MANDATORY: return 0 -> no Error).
>   *
>   */
> int32_t iis2iclx_fifo_out_raw_get(stmdev_ctx_t *ctx, uint8_t *buff)
> {
>   int32_t ret;
> 
>   ret = iis2iclx_read_reg(ctx, IIS2ICLX_FIFO_DATA_OUT_X_L, buff, 6);
> 
>   return ret;
> }
> ```

Yes, the loop must be done outside. You can refer to following example, which uses similar API:
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dso_STdC/examples/lsm6dso_fifo.c

**Comment by WadeHenderson** [comment]
Oh I see, it is pulling out each axis measurement on every read. Thanks!
